name: SmartDns

on:
  watch:
    types: started

env:
  REPO_URL: https://github.com/pymumu/smartdns/
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_SH: diy.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  TZ: Asia/Shanghai
  LUCI: luci-compat
  PLATFORM: openwrt
  ARCH: mipsel_24kc

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    - name: Clone source code
      run: git clone $REPO_URL -b $REPO_BRANCH smartdns

#    - name: Load custom configuration
#      run: |
#        [ -e files ] && mv files smartdns/files
#        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE smartdns/.config
#        chmod +x $DIY_SH
#        cd smartdns
#        ../$DIY_SH


    - name: SSH connection to Actions
      uses: LeePapa/debugger-action@master
      if: env.SSH_ACTIONS == 'true'
      
    - name: Compile the firmware
      id: compile
      run: |
        cd smartdns
        mkdir target
        chmod +x package/build-pkg.sh
        package/build-pkg.sh '$0 --platform' $LUCI '--arch' $ARCH '--outputdir' $PWD/target
        package/build-pkg.sh '$0 --platform' $PLATFORM '--arch' $ARCH '--outputdir' $PWD/target
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && !cancelled()
      with:
        name: $PLATFORM-$ARCH-SmartDns_bin
        path: smartdns/target
